version: '2'

services:
  application:
    container_name: application
    image: 'philharmonic:latest'
    build:
      context: .
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8080:8080"

  database:
    container_name: database
    image: 'postgres:13.3'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
