CREATE SEQUENCE cultural_building_sequence START 7 INCREMENT 50;

CREATE SEQUENCE event_sequence START 6 INCREMENT 50;

CREATE SEQUENCE artist_sequence START 11 INCREMENT 50;

CREATE SEQUENCE genre_sequence START 8 INCREMENT 50;

CREATE SEQUENCE impresario_sequence START 11 INCREMENT 50;

CREATE SEQUENCE organizer_sequence START 11 INCREMENT 50;
